remote_theme: aterenin/minima-reboot
title: first_page
author: Otsuka Hiro
description: test
url: https://hung19091.github.io
baseurl: "/skills-github-pages"
minima_reboot:
  date_format: "%Y-%m-%d"
  date_format_short: "%m-%d"
defaults: # 将所有配置选项使用<https://jekyllrb.com/docs/configuration/front-matter-defaults/>功能进行配置
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values: 
      layout: "post"
header_pages:
- posts.md
