remote_theme: aterenin/minima-reboot
title: first_page
author: Otsuka Hiro
description: test
url: https://hung19091.github.io
baseurl: "/skills-github-pages"
minima_reboot:
  date_format: "%Y-%m-%d"
  date_format_short: "%m-%d"
  comments: # 留言页，请先修改这里，确保使用的是你自己的repo！参照<https://utteranc.es/>
        append: |
          <script
            repo="hung19091/blog_comment"
            src="https://utteranc.es/client.js"
            issue-term="url"
            theme="github-light"
            crossorigin="anonymous"
            async="async"
          ></script>
