remote_theme: aterenin/minima-reboot
title: first_page
author: Otsuka Hiro
description: test
minima_reboot:
  date_format: "%Y-%m-%d"
  date_format_short: "%m-%d"
url: https://hung19091.github.io
baseurl: "/skills-github-pages"
defaults:
  append: |
    <script
      repo="hung19091/blog_comment"
      src="https://utteranc.es/client.js"
      issue-term="url"
      theme="github-light"
      crossorigin="anonymous"
      async="async"
    ></script>
